version: '3.8'

services:
  backend:
    container_name: time-booking-backend
    build:
      context: .
      dockerfile: Dockerfile.dev
      # platform: linux/amd64
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    container_name: lab_booking_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lab_booking
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
